USE [PatientCheckIn];

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;
SET ANSI_NULLS ON;

GO

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
           WHERE TABLE_NAME = 'ProvinceCity'))
	BEGIN
		PRINT 'Table ProviceCity exists'
	END

ELSE 
	BEGIN 
		CREATE TABLE [dbo].[ProvinceCity](
			[ProvinceCityID] [int] IDENTITY(1,1) NOT NULL,
			[ProvinceCityName] [nvarchar](100) NOT NULL,
		PRIMARY KEY CLUSTERED 
		(
			[ProvinceCityID] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
		) ON [PRIMARY]
	END